---
ID: "f01948f0-7493-41e6-93a9-83fd8a69adca"
Parent: "c74d013d-6045-4d73-82b8-f6a5cba4c483"
Template: "3a45a723-64ee-4919-9d41-02fd40fd1466"
Path: /sitecore/layout/Layouts/Project/DemoSite/Default
DB: master
SharedFields:
- ID: "a036b2bc-ba04-44f6-a75f-bae6cd242abf"
  Hint: Path
  Value: /Views/Shared/Default.cshtml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190901T183511Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
